Repository ProjectWarhol/backend, pull requests merged in 2022-11, with the labels that each got.

#141 Feature/pm2/ci
  .env.example
  .github/workflows/ci.yml
  app/models/index.js
  config/config.js
  ecosystem.config.js
  package.json
Labels: enhancement

#140 Feature/nftcontent tags companies
  app/controllers/content.controller.js
  app/models/company.js
  app/models/nft.content.js
  app/routes/company.routes.js
  app/routes/content.routes.js
  app/routes/main.js
  db/migrations/4-createNftContent.js
  db/seeders/1-users.js
  db/seeders/4-nft.content.js
Labels: enhancement

#146 Add a ci/cd section on the Readme
  README.md
Labels: documentation

#147 feat: implemented cors policy
  app.js
Labels: enhancement

#148 Edit Deploy section on ci.yml
  .github/workflows/ci.yml
Labels: bug, enhancement
