Repository ProjectWarhol/backend, pull requests merged in 2022-10, with the labels that each got.

#125 Feature/security header
  .github/workflows/ci.yml
  app.js
  app/middlewares/headers.middleware.js
Labels: enhancement

#130 Feature/deployment/docker new setup
  .dockerignore
  .env.example
  .github/workflows/ci.yml
  Dockerfile
  app/helpers/env.handler.js
  app/models/index.js
  docker-compose.yml
Labels: enhancement

#134 update: JobPositon-table-model+mig+seeder
  .github/workflows/ci.yml
  app/helpers/env.handler.js
  app/models/company.js
  app/models/index.js
  app/models/job.position.js
  app/models/user.js
  app/service/user.account.js
  db/migrations/1-createUser.js
  db/migrations/3-createJobPosition.js
  db/migrations/8-User_companyId_fk.js
  db/seeders/3-job.position.js
  db/seeders/4-nft.content.js
  db/seeders/5-comments.js
  db/seeders/6-nft.vote.js
  db/seeders/7-promoting.js
Labels: enhancement

#136 feature/passport integration
  app.js
  app/controllers/session.controller.js
  app/middlewares/authentication.middleware.js
  app/middlewares/authorization.middleware.js
  app/passport/setup.js
  app/passport/strategies.js
  app/routes/user.routes.js
  package.json
Labels: enhancement, refactor

#137 Feature/config/env/integration
  .env.example
  .gitignore
  README.md
  app.js
  app/helpers/env.handler.js
  app/models/index.js
  config/config.js
  package.json
Labels: bug, enhancement

#139 Bug/config/ca certificate
  app/helpers/env.handler.js
  app/models/index.js
  app/util/env.handler.js
  app/util/readFile.js
  config/config.js
Labels: bug
